import React, { useState, useEffect } from 'react';
import { Trash2, Download } from 'lucide-react';

interface CogsItem {
  id: string;
  description: string;
  quantity: number;
  rate: number;
  cogs: number;
}

const CogsSheet: React.FC = () => {
  const [cogsItems, setCogsItems] = useState<CogsItem[]>([]);

  useEffect(() => {
    const stored = localStorage.getItem('numera_cogs');
    if (stored) {
      setCogsItems(JSON.parse(stored));
    }
  }, []);

  const removeItem = (id: string) => {
    const updated = cogsItems.filter(item => item.id !== id);
    setCogsItems(updated);
    localStorage.setItem('numera_cogs', JSON.stringify(updated));
  };

  const totalRevenue = cogsItems.reduce((sum, item) => sum + (item.quantity * item.rate), 0);
  const totalCogs = cogsItems.reduce((sum, item) => sum + (item.quantity * item.cogs), 0);
  const totalProfit = totalRevenue - totalCogs;
  const profitMargin = totalRevenue > 0 ? ((totalProfit / totalRevenue) * 100).toFixed(1) : '0.0';

  const exportToText = () => {
    const date = new Date().toLocaleDateString();
    const content = `
═══════════════════════════════════════════════════════════════
                        COGS SHEET
═══════════════════════════════════════════════════════════════

Date Generated: ${date}
Total Items: ${cogsItems.length}

───────────────────────────────────────────────────────────────
COST OF GOODS SOLD BREAKDOWN
───────────────────────────────────────────────────────────────

${cogsItems.length > 0 ? cogsItems.map((item, idx) => 
  `${idx + 1}. ${item.description}
   Quantity: ${item.quantity}
   Unit Price: $${item.rate.toFixed(2)}
   Unit COGS: $${item.cogs.toFixed(2)}
   Line Revenue: $${(item.quantity * item.rate).toFixed(2)}
   Line COGS: $${(item.quantity * item.cogs).toFixed(2)}
   Line Profit: $${(item.quantity * (item.rate - item.cogs)).toFixed(2)}
   Margin: ${((((item.rate - item.cogs) / item.rate) * 100) || 0).toFixed(1)}%`
).join('\n\n') : 'No items tracked yet.'}

═══════════════════════════════════════════════════════════════
TOTALS
═══════════════════════════════════════════════════════════════

Total Revenue:                                  $${totalRevenue.toFixed(2)}
Total COGS:                                     $${totalCogs.toFixed(2)}
Total Profit:                                   $${totalProfit.toFixed(2)}
Profit Margin:                                  ${profitMargin}%

═══════════════════════════════════════════════════════════════
Generated by Numera - COGS Tracking
═══════════════════════════════════════════════════════════════
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `cogs-sheet-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      <div className="bg-blue-50 border-2 border-blue-300 p-4">
        <h3 className="font-bold uppercase text-sm">📊 Cost Of Goods Sold</h3>
        <p className="text-xs text-gray-600 mt-1">Track all line items from invoices. Auto-populated when items are added to the Invoice Generator.</p>
      </div>

      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        <div className="border-2 border-black p-3 text-center">
          <span className="text-xs font-bold uppercase text-gray-500 block mb-1">Total Items</span>
          <span className="text-2xl font-mono font-bold">{cogsItems.length}</span>
        </div>
        <div className="border-2 border-black p-3 text-center">
          <span className="text-xs font-bold uppercase text-gray-500 block mb-1">Revenue</span>
          <span className="text-2xl font-mono font-bold">${totalRevenue.toFixed(0)}</span>
        </div>
        <div className="border-2 border-black p-3 text-center">
          <span className="text-xs font-bold uppercase text-gray-500 block mb-1">COGS</span>
          <span className="text-2xl font-mono font-bold">${totalCogs.toFixed(0)}</span>
        </div>
        <div className="border-2 border-black p-3 text-center bg-green-50">
          <span className="text-xs font-bold uppercase text-gray-500 block mb-1">Profit</span>
          <span className="text-2xl font-mono font-bold text-green-700">${totalProfit.toFixed(0)}</span>
        </div>
      </div>

      {cogsItems.length === 0 ? (
        <div className="text-center py-12 text-gray-400 border-2 border-dashed border-gray-300">
          <p className="text-sm font-bold uppercase">No items tracked yet</p>
          <p className="text-xs text-gray-400 mt-2">Add items via the Invoice Generator</p>
        </div>
      ) : (
        <div className="space-y-2">
          {cogsItems.map((item) => (
            <div key={item.id} className="border-2 border-black p-4 space-y-2">
              <div className="flex justify-between items-start">
                <div className="flex-1">
                  <div className="font-bold uppercase text-sm">{item.description}</div>
                  <div className="font-mono text-xs text-gray-600 mt-1">
                    Qty: {item.quantity} | Rate: ${item.rate.toFixed(2)} | COGS: ${item.cogs.toFixed(2)}
                  </div>
                </div>
                <button
                  onClick={() => removeItem(item.id)}
                  className="text-red-500 hover:text-red-700 ml-2"
                >
                  <Trash2 size={16} strokeWidth={2.5} />
                </button>
              </div>
              <div className="grid grid-cols-3 gap-2 font-mono text-sm pt-2 border-t border-gray-300">
                <div>
                  <span className="text-xs text-gray-500">Revenue</span>
                  <div className="font-bold">${(item.quantity * item.rate).toFixed(2)}</div>
                </div>
                <div>
                  <span className="text-xs text-gray-500">COGS</span>
                  <div className="font-bold">${(item.quantity * item.cogs).toFixed(2)}</div>
                </div>
                <div>
                  <span className="text-xs text-gray-500">Profit</span>
                  <div className="font-bold text-green-700">${(item.quantity * (item.rate - item.cogs)).toFixed(2)}</div>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}

      {cogsItems.length > 0 && (
        <div className="border-t-2 border-black pt-4 space-y-3">
          <div className="grid grid-cols-2 gap-4 font-mono text-sm">
            <div className="border-2 border-black p-3">
              <span className="text-xs font-bold uppercase text-gray-500 block mb-1">Margin %</span>
              <span className="text-3xl font-bold text-green-700">{profitMargin}%</span>
            </div>
            <div className="border-2 border-black p-3">
              <span className="text-xs font-bold uppercase text-gray-500 block mb-1">Avg Item Profit</span>
              <span className="text-3xl font-bold">${(totalProfit / cogsItems.length).toFixed(2)}</span>
            </div>
          </div>

          <div className="flex gap-2">
            <button
              onClick={exportToText}
              className="flex-1 px-6 py-3 bg-black text-white font-bold uppercase hover:bg-gray-800 transition-colors flex items-center justify-center gap-2"
            >
              <Download size={20} strokeWidth={2.5} />
              Export Sheet
            </button>
            <button
              onClick={() => {
                if (window.confirm('Clear all COGS items? This cannot be undone.')) {
                  setCogsItems([]);
                  localStorage.setItem('numera_cogs', JSON.stringify([]));
                }
              }}
              className="px-6 py-3 bg-red-600 text-white font-bold uppercase hover:bg-red-700 transition-colors"
            >
              Clear All
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

export default CogsSheet;
