import React, { useState, useEffect } from 'react';
import { Plus, Trash2, Download, Package } from 'lucide-react';

interface Material {
  id: string;
  name: string;
  supplier: string;
  costPrice: number;
  markup: number; // percentage
  quantity: number;
  unit: string;
}

const MaterialsSheet: React.FC = () => {
  const [materials, setMaterials] = useState<Material[]>([]);
  const [projectName, setProjectName] = useState('');
  const [defaultMarkup, setDefaultMarkup] = useState(30);
  const [newMaterial, setNewMaterial] = useState({
    name: '',
    supplier: '',
    costPrice: 0,
    markup: defaultMarkup,
    quantity: 1,
    unit: 'ea',
  });

  useEffect(() => {
    const saved = localStorage.getItem('numera_materials_sheet');
    if (saved) {
      const data = JSON.parse(saved);
      setMaterials(data.materials || []);
      setProjectName(data.projectName || '');
      setDefaultMarkup(data.defaultMarkup || 30);
    }
  }, []);

  useEffect(() => {
    localStorage.setItem('numera_materials_sheet', JSON.stringify({
      materials,
      projectName,
      defaultMarkup,
    }));
  }, [materials, projectName, defaultMarkup]);

  const addMaterial = () => {
    if (!newMaterial.name.trim()) return;

    const material: Material = {
      id: Date.now().toString(),
      ...newMaterial,
    };

    setMaterials([...materials, material]);
    setNewMaterial({
      name: '',
      supplier: '',
      costPrice: 0,
      markup: defaultMarkup,
      quantity: 1,
      unit: 'ea',
    });
  };

  const removeMaterial = (id: string) => {
    setMaterials(materials.filter(m => m.id !== id));
  };

  const updateMaterial = (id: string, field: keyof Material, value: string | number) => {
    setMaterials(materials.map(m =>
      m.id === id ? { ...m, [field]: value } : m
    ));
  };

  const calculateSellPrice = (costPrice: number, markup: number) => {
    return costPrice * (1 + markup / 100);
  };

  const totalCost = materials.reduce((sum, m) => sum + (m.costPrice * m.quantity), 0);
  const totalSell = materials.reduce((sum, m) => 
    sum + (calculateSellPrice(m.costPrice, m.markup) * m.quantity), 0
  );
  const totalProfit = totalSell - totalCost;
  const averageMarkup = totalCost > 0 ? ((totalProfit / totalCost) * 100) : 0;

  const exportToText = () => {
    const date = new Date().toLocaleDateString();
    const content = `
═══════════════════════════════════════════════════════════════
                      MATERIALS SHEET
═══════════════════════════════════════════════════════════════

Date: ${date}
${projectName ? `Project: ${projectName}` : 'Project: [Not Specified]'}

───────────────────────────────────────────────────────────────
MATERIALS LIST
───────────────────────────────────────────────────────────────

${materials.length > 0 ? materials.map((material, idx) => {
  const sellPrice = calculateSellPrice(material.costPrice, material.markup);
  const lineTotal = sellPrice * material.quantity;
  return `${idx + 1}. ${material.name}
   Supplier: ${material.supplier || 'N/A'}
   Quantity: ${material.quantity} ${material.unit}
   Cost Price: $${material.costPrice.toFixed(2)} / ${material.unit}
   Markup: ${material.markup}%
   Sell Price: $${sellPrice.toFixed(2)} / ${material.unit}
   Line Total: $${lineTotal.toFixed(2)}`;
}).join('\n\n') : 'No materials added yet.'}

───────────────────────────────────────────────────────────────
SUMMARY
───────────────────────────────────────────────────────────────

Total Cost:                                     $${totalCost.toFixed(2)}
Total Sell Price:                               $${totalSell.toFixed(2)}
Gross Profit:                                   $${totalProfit.toFixed(2)}
Average Markup:                                 ${averageMarkup.toFixed(1)}%

═══════════════════════════════════════════════════════════════
Generated by Numera - Business Finance Platform
═══════════════════════════════════════════════════════════════
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    const filename = `materials-${projectName ? projectName.toLowerCase().replace(/\s+/g, '-') : 'sheet'}-${Date.now()}.txt`;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      <div className="bg-purple-50 border-2 border-purple-300 p-4">
        <div className="flex items-start gap-2">
          <Package size={20} className="text-purple-600 flex-shrink-0 mt-0.5" strokeWidth={2.5} />
          <p className="text-sm text-purple-900">
            <strong>Materials Tracking:</strong> Track supplier costs and add your markup to calculate selling prices. 
            Perfect for contractors managing material costs across multiple projects.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-bold uppercase mb-2">Project Name</label>
          <input
            type="text"
            value={projectName}
            onChange={(e) => setProjectName(e.target.value)}
            placeholder="Enter project name"
            className="w-full px-4 py-2 border-2 border-black focus:ring-2 focus:ring-black focus:outline-none font-mono"
          />
        </div>
        <div>
          <label className="block text-sm font-bold uppercase mb-2">Default Markup (%)</label>
          <input
            type="number"
            value={defaultMarkup}
            onChange={(e) => {
              const value = Number(e.target.value);
              setDefaultMarkup(value);
              setNewMaterial({ ...newMaterial, markup: value });
            }}
            className="w-full px-4 py-2 border-2 border-black focus:ring-2 focus:ring-black focus:outline-none font-mono"
            min="0"
            max="999"
          />
        </div>
      </div>

      <div className="border-2 border-black p-4 bg-gray-50">
        <h3 className="text-sm font-bold uppercase mb-4">Add Material</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
          <input
            type="text"
            placeholder="Material name"
            value={newMaterial.name}
            onChange={(e) => setNewMaterial({ ...newMaterial, name: e.target.value })}
            onKeyPress={(e) => e.key === 'Enter' && addMaterial()}
            className="px-3 py-2 border-2 border-black focus:ring-2 focus:ring-black focus:outline-none font-mono text-sm"
          />
          <input
            type="text"
            placeholder="Supplier"
            value={newMaterial.supplier}
            onChange={(e) => setNewMaterial({ ...newMaterial, supplier: e.target.value })}
            className="px-3 py-2 border-2 border-black focus:ring-2 focus:ring-black focus:outline-none font-mono text-sm"
          />
          <div className="flex gap-2">
            <input
              type="number"
              placeholder="Qty"
              value={newMaterial.quantity}
              onChange={(e) => setNewMaterial({ ...newMaterial, quantity: Number(e.target.value) })}
              className="w-20 px-3 py-2 border-2 border-black focus:ring-2 focus:ring-black focus:outline-none font-mono text-sm"
              min="0"
              step="1"
            />
            <select
              value={newMaterial.unit}
              onChange={(e) => setNewMaterial({ ...newMaterial, unit: e.target.value })}
              className="flex-1 px-3 py-2 border-2 border-black focus:ring-2 focus:ring-black focus:outline-none font-mono text-sm"
            >
              <option value="ea">Each</option>
              <option value="ft">Feet</option>
              <option value="yd">Yards</option>
              <option value="lb">Pounds</option>
              <option value="box">Box</option>
              <option value="bag">Bag</option>
              <option value="roll">Roll</option>
            </select>
          </div>
          <input
            type="number"
            placeholder="Cost price"
            value={newMaterial.costPrice || ''}
            onChange={(e) => setNewMaterial({ ...newMaterial, costPrice: Number(e.target.value) })}
            className="px-3 py-2 border-2 border-black focus:ring-2 focus:ring-black focus:outline-none font-mono text-sm"
            min="0"
            step="0.01"
          />
          <input
            type="number"
            placeholder="Markup %"
            value={newMaterial.markup}
            onChange={(e) => setNewMaterial({ ...newMaterial, markup: Number(e.target.value) })}
            className="px-3 py-2 border-2 border-black focus:ring-2 focus:ring-black focus:outline-none font-mono text-sm"
            min="0"
            max="999"
          />
          <button
            onClick={addMaterial}
            className="px-4 py-2 bg-black text-white font-bold uppercase text-sm hover:bg-gray-800 transition-colors flex items-center justify-center gap-2"
          >
            <Plus size={16} strokeWidth={2.5} />
            Add
          </button>
        </div>
      </div>

      {materials.length > 0 && (
        <>
          <div className="border-2 border-black overflow-hidden">
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead>
                  <tr className="bg-black text-white">
                    <th className="px-3 py-2 text-left text-xs font-bold uppercase">Material</th>
                    <th className="px-3 py-2 text-left text-xs font-bold uppercase">Supplier</th>
                    <th className="px-3 py-2 text-right text-xs font-bold uppercase">Qty</th>
                    <th className="px-3 py-2 text-right text-xs font-bold uppercase">Cost</th>
                    <th className="px-3 py-2 text-right text-xs font-bold uppercase">Markup</th>
                    <th className="px-3 py-2 text-right text-xs font-bold uppercase">Sell Price</th>
                    <th className="px-3 py-2 text-right text-xs font-bold uppercase">Total</th>
                    <th className="px-3 py-2 text-center text-xs font-bold uppercase w-12"></th>
                  </tr>
                </thead>
                <tbody className="bg-white">
                  {materials.map((material, idx) => {
                    const sellPrice = calculateSellPrice(material.costPrice, material.markup);
                    const lineTotal = sellPrice * material.quantity;
                    return (
                      <tr key={material.id} className={idx % 2 === 0 ? 'bg-gray-50' : 'bg-white'}>
                        <td className="px-3 py-2 font-mono text-sm">{material.name}</td>
                        <td className="px-3 py-2 font-mono text-sm text-gray-600">{material.supplier}</td>
                        <td className="px-3 py-2 font-mono text-sm text-right">
                          {material.quantity} {material.unit}
                        </td>
                        <td className="px-3 py-2 font-mono text-sm text-right">
                          ${material.costPrice.toFixed(2)}
                        </td>
                        <td className="px-3 py-2 font-mono text-sm text-right text-green-600 font-bold">
                          {material.markup}%
                        </td>
                        <td className="px-3 py-2 font-mono text-sm text-right font-bold">
                          ${sellPrice.toFixed(2)}
                        </td>
                        <td className="px-3 py-2 font-mono text-sm text-right font-bold">
                          ${lineTotal.toFixed(2)}
                        </td>
                        <td className="px-3 py-2 text-center">
                          <button
                            onClick={() => removeMaterial(material.id)}
                            className="text-red-600 hover:text-red-800 transition-colors"
                          >
                            <Trash2 size={16} strokeWidth={2.5} />
                          </button>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </div>

          <div className="border-2 border-black p-6 bg-gray-900 text-white">
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              <div>
                <p className="text-xs uppercase font-bold text-gray-400 mb-1">Total Cost</p>
                <p className="text-2xl font-mono font-bold">${totalCost.toFixed(2)}</p>
              </div>
              <div>
                <p className="text-xs uppercase font-bold text-gray-400 mb-1">Total Sell</p>
                <p className="text-2xl font-mono font-bold text-green-400">${totalSell.toFixed(2)}</p>
              </div>
              <div>
                <p className="text-xs uppercase font-bold text-gray-400 mb-1">Gross Profit</p>
                <p className="text-2xl font-mono font-bold text-purple-400">${totalProfit.toFixed(2)}</p>
              </div>
              <div>
                <p className="text-xs uppercase font-bold text-gray-400 mb-1">Avg Markup</p>
                <p className="text-2xl font-mono font-bold text-blue-400">{averageMarkup.toFixed(1)}%</p>
              </div>
            </div>
          </div>

          <button
            onClick={exportToText}
            className="w-full px-6 py-3 bg-black text-white font-bold uppercase hover:bg-gray-800 transition-colors flex items-center justify-center gap-2"
          >
            <Download size={20} strokeWidth={2.5} />
            Export Materials Sheet
          </button>
        </>
      )}

      {materials.length === 0 && (
        <div className="text-center py-12 text-gray-400 border-2 border-dashed border-gray-300">
          <Package size={48} className="mx-auto mb-4 text-gray-300" strokeWidth={1.5} />
          <p className="text-lg font-bold uppercase">No Materials Yet</p>
          <p className="text-sm">Add your first material above to get started</p>
        </div>
      )}
    </div>
  );
};

export default MaterialsSheet;
